### ISSUE TITLE
The Algorithmic Engine (AE) supports the "entry_point = ds".

### ISSUE THREAD

**Issue by simoneratti** [geometryglobal-emea/pathfinder-algorithm#2]
For the moment focus only on the entry point "ds". Write the code that reads the entry_point configuration and if the value is "ds" loads the sqlite database pointed by "input_file" into the Algorithmic Engine. 

Prepare the logic in "dc.rb" which branches the code based on the "entry_point". For the moment finalise the workflow for the "ds" value only. 

"bpm", "pdjm", "visualisation" are dummy procedures returning an error message

**Comment by huskebasi** [comment]
The code now supports the selective execution of ds if entry_point and
exit_point == ds.
Removed from the opt_parser command-line help the -d option relative to
the database path.
