### ISSUE TITLE
Write the code to support the creation of the dumpDS.js.

### ISSUE THREAD

**Issue by simoneratti** [geometryglobal-emea/pathfinder-algorithm#5]
The AE must be able to create the dumpDS.js JSON file which contains all the data contained in the dumpDS.js template.

**Comment by huskebasi** [comment]
The "dump_ds.js" file contains all the configuration' parameters of the ds phase, an array with every record's coule "dat_object_id" and "res_dynamic_segment_id" columns.
Furthermore it contains the YAML serialization of the "dyn_segs" variable and the 'bpm' phase is capable of reading and parsing it back to the "dyn_segs" pointer.
